### ISSUE TITLE
Shitchain endpoint object name incorrect

### ISSUE THREAD

**Issue by magnetism2000** [KipCrossing/voting-app-api#5]
https://1j56c60pb0.execute-api.ap-southeast-2.amazonaws.com/dev/shitchain

Returns:
response_ballots as main key for data

Needs to change to 'data' to keep in api standards

**Comment by KipCrossing** [comment]
Will do this today

**Comment by KipCrossing** [comment]
@oscarmanderj want me to do the same with the results endpoint too?

**Comment by KipCrossing** [comment]
Done, it is now just a list
